bndw/wifi-card

src/components/Card.js
src/components/style.css

Serif font for input fields

---

src/components/Card.js

Escapes special characters `";,:\`
Fixes #3

:bug: Escape special chars

---

.dockerignore
yarn.lock

Resolves https://github.com/advisories/GHSA-cwx2-736x-mf6w

Update object path

---

src/components/Card.js
src/components/style.css
src/style.css

Adds a rotate button that toggles landscape and portrait orientation.
Fixes #30

Portrait orientation

---

src/components/Card.js
src/components/style.css

https://github.com/bndw/wifi-card/pull/37 with review feedback implemented.

Hide password before printing

---

README.md

Document local dev setup + Prettier commands

Local development setup

---

Makefile
README.md

Prefer Make as the entrypoint for common commands.

Add make targets for prettier formatting

---

src/components/Card.js

Addresses changes requested by issue #51. Note that the network name is checked before the password.

Add check for non-null network name

---

src/components/Card.js

Unset password when encryption mode is 'None'

---

src/components/Card.js

fix: unmatched title

---

src/i18n.js
yarn.lock

Use english as a fallback language

---

README.md

Documents supported languages in the README with credit to the authors. Please let me know if you'd prefer your Github username not listed.
cc: 
- @Baoyuantop
- @oscfdezdz 
- @pedrorenan
- @hatsu38
- @Teraskull 
- @wouterbrink
Also, thanks @Teraskull for the inspiration for this in https://github.com/Teraskull/PyDebloatX

Document supported languages

---

src/App.js
src/i18n.js

Sorry for another PR, but the last change made a lot of conflits then I prefer to delete and make again without errors

pt-BR translation

---

README.md
src/App.js
src/i18n.js

Hey :wave:,
This PR adds the **French (fr-FR)** translation.

feat(i18n): add French (fr-FR)

---

src/components/Card.js

FYI: https://reactjs.org/docs/dom-elements.html#htmlfor

label attribute for->htmlFor

---

src/components/Card.js

change for loop to for-of : https://github.com/bndw/wifi-card/issues/93

fix for loop to for-of - SonarLint warning

---

src/App.js

Includes Hindi to resolve conflict from https://github.com/bndw/wifi-card/pull/81

Make language display consistent

---

README.md
src/App.js
src/i18n.js

Fixes up https://github.com/bndw/wifi-card/pull/84

Catalan translation

---

README.md
src/components/Card.js
src/components/style.css

Cleans up conflicts/rebase from https://github.com/bndw/wifi-card/pull/87
Fixes https://github.com/bndw/wifi-card/issues/82

QR Code sharpness

---

README.md
src/App.js
src/i18n.js

Resolves conflicts from https://github.com/bndw/wifi-card/pull/98
Fixes https://github.com/bndw/wifi-card/issues/104

German translation

---

README.md
src/App.js
src/i18n.js

Resolves conflicts in https://github.com/bndw/wifi-card/pull/123

Indonesia translation

---

README.md
src/App.js
src/i18n.js

Resolves conflicts from https://github.com/bndw/wifi-card/pull/116

Polish translation

---

README.md
src/App.js
src/i18n.js

Resolves conflicts in https://github.com/bndw/wifi-card/pull/122

Occitan translation

---

src/components/Card.js

- 🐛 Fix RTL bug where encryption mode selected does not match that on the QR code due to direction misalignment.

🐛 fix rtl direction bugs

---

README.md
src/App.js
src/i18n.js

Resolves conflicts in https://github.com/bndw/wifi-card/pull/130

Italian translation

---

public/index.html

- ✨ add desc attribute to index.html

✨ add desc attribute to index.html

---

.husky/pre-commit
package.json
yarn.lock

- 🔨 add husky precommit to auto run prettier
We can now remove the 3rd step here https://github.com/bndw/wifi-card/issues/117

🔨 add husky precommit to auto run prettier

---

public/index.html

Page descriptions belong in a meta tag.
cc: @A-Tokyo

Update meta desc

---

README.md

- 📚 update docs with automated configs

📚 update docs with automated configs

---

src/i18n.js

Resolves conflicts in https://github.com/bndw/wifi-card/pull/136

Update support for portuguese language

---

README.md
src/components/Card.js

feat: add Language contribution guide in README

---

src/App.js
src/i18n.js

Rename 'en' to 'en-US'

---

src/components/Card.js

code refactoring proposal

---

src/components/Card.js
src/i18n.js

Translate encryption mode 'None'

---

src/components/Card.js

Quick and temporary rotation fix for https://github.com/bndw/wifi-card/issues/161. 
This change has an effect on https://github.com/bndw/wifi-card/pull/87.

fast and temporary rotation fix 

---

src/i18n.js

Fixes #158
Hi @bndw @Teraskull, how does this look?
Let me know if this needs any changes.
Thanks

Made few translation corrections

---

README.md
src/App.js
src/i18n.js

This is a simple contribution to the Korean translation.
Thanks for a good open source.

🇰🇷 Add Korean translation

---

README.md
package.json

Dependencies update to the latest versions. This seems to be beneficial for the project.
I use [vscode-versionlens](https://gitlab.com/versionlens/vscode-versionlens) to search for the latest versions.

bump up dependencies versions to newest

---

README.md
src/App.js
src/components/Card.js
src/i18n.js

I've punched up the Norwegian translation as I want my family and friends to print their own cards.. ;)

✨ Adds Norwegian translation.

---

README.md

Update readme with hungarian translation

---

README.md
src/translations.js

Hi, I've added support for the Serbian language with both Latin and Cyrillic writing.

Add support for Serbian language

---

src/translations.js

French (fr-FR) for #171 
Don't hesitate to @ me when there is translation to do for the French language. :smile:

feat(i18n): update French (fr-FR)

---

src/translations.js

Spanish and Hungarian

---

src/App.js

Fixes #201
@A-Tokyo Would you mind confirming this resolves the bug? It's currently deployed at https://dev.wificard.io

Ensure page direction is set properly on first load

---

src/App.js
src/components/WifiCard.js

@A-Tokyo Alternative implementation of https://github.com/bndw/wifi-card/pull/202
Fixes #203

Always add paddingRight for rtl 

---

src/translations.js

@PushpenderSaini0 @pedrorenan @ismaelpereira

Update Hindi and Portuguese translations

---

README.md
src/translations.js

🌐  translation: Add Thai language

---

src/translations.js

🌐  update: Change some words for better understanding in Thai language.

---

src/translations.js

translation: update Turkish

---

README.md
src/translations.js

Add translation for Traditional Chinese Taiwan (zh-TW)

Add Traditional Chinese (Taiwan) translations

---

src/App.js

refactor: optimize some codes in `./src/App.js`

refactor: optimize some codes

---

src/App.js
src/components/Settings.js
src/components/WifiCard.js
src/translations.js

I added support for WPA2-EAP authentication with the PWD method. I also added a German translation of the new strings. Other languages will have to be updated by someone who knows them.
When the EAP method and identity fields are hidden there is a small additional gap that I don't know how to get rid of. If that is an issue, I would appreciate some help with fixing that.

Add support for EAP-PWD

---

README.md
src/translations.js

Replaces https://github.com/bndw/wifi-card/pull/242
Fixes #241

feat(translation): Demark Danish

---

src/components/style.css

For issue #250, added margin between checkboxes, radio boxes, and text which was getting messed up when RTL-based language was selected

Added margin between checkbox, radio box and text

---

README.md
src/translations.js

Fixes lint error in https://github.com/bndw/wifi-card/pull/252

Greek translation

---

src/translations.js

Replaces https://github.com/bndw/wifi-card/pull/254

i18n: update for Occitan

---

Dockerfile
package.json

Use the official node for building and bump to latest node LTS version

Use official node image
